# Generated by Django 5.2 on 2025-05-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('account_status', models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard')], default='standard', max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('current_partner_requests', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('required_players', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lifetime', models.IntegerField()),
                ('platform', models.CharField(choices=[('PC', 'PC'), ('Console', 'Console'), ('Mobile', 'Mobile')], max_length=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
